from assis import Lucy,Search

Lucy(Lucy().listen())
Lucy("open d drivers")
Lucy("search folder name python")
Lucy("search drivers")
Lucy("search file name django")
Lucy("open chrome applications")
Lucy("search on web face")
Lucy("search on web python programming")
Search("search driver")
Search("search folder name python")
Search("search file name python")
Search("search all folder")
Lucy().talk("hello everyone")
Lucy().talk("hello everyone",sleep = False)
data = Lucy().listen("can i help yoo ?")
data = Lucy().listen()
read = Lucy().read("read this messages .")
